const answer1 = 'Котик' > 'котик' ? 'true' : 'false';
const answer2 = 'Котик' < 'китик' ? 'true' : 'false';
const answer3 = 'Кот' > 'Котик' ? 'true' : 'false';
const answer4 = 'Привет' != 'Пока' ? 'true' : 'false';
const answer5 = 73 > '53' ? 'true' : 'false';
const answer6 = false < 0 ? 'true' : 'false';
const answer7 = 54 > true ? 'true' : 'false';
const answer8 = 123 == false ? 'true' : 'false';
const answer9 = true > '3' ? 'true' : 'false';
const answer10 = 3 != '5мм' ? 'true' : 'false';
const answer11 = 8 < '-2' ? 'true' : 'false';
const answer12 = 34 == '34' ? 'true' : 'false';
const answer13 = null === undefined ? 'true' : 'false';
console.log(answer1);
console.log(answer2);
console.log(answer3);
console.log(answer4);
console.log(answer5);
console.log(answer6);
console.log(answer7);
console.log(answer8);
console.log(answer9);
console.log(answer10);
console.log(answer11);
console.log(answer12);
console.log(answer13);