let a = 5;
let myname = "Name";
let i = 0;
let double = 0.23;
let result = 1/0;
let answer = true;
let no = null;
console.log(typeof a);
console.log(typeof myname);
console.log(typeof i);
console.log(typeof double);
console.log(typeof result);
console.log(typeof answer);
console.log(typeof no);